//! Crossplane controller Go-code emitter.
//!
//! Produces a single `<resource>_controller.go` file per `IacResource`,
//! implementing the `crossplane-runtime` `ExternalClient` interface
//! (Observe / Create / Update / Delete) wrapped around calls into the
//! resource's autogenerated SDK (akeyless-go for the akeyless provider,
//! datadog-go-sdk for the future datadog provider, etc.).
//!
//! ## Layering
//!
//! - **iac-forge** owns the IR ([`IacResource`], [`IacProvider`]).
//! - **iac-forge::sdk_naming** owns the per-language SDK symbol
//!   convention.
//! - **crossplane-forge::crd** owns the schema-side emission (CRD YAML).
//! - **crossplane-forge::controller_gen** (this module) owns the
//!   runtime-side emission (Go reconciler code).
//!
//! ## Status (slice 1)
//!
//! This first slice produces a controller skeleton with the correct
//! method signatures, package declaration, imports, and SDK call
//! shapes. Method bodies carry inline TODO markers for the
//! field-mapping logic — controller emission against the IR's
//! `attributes` + `read_mapping` lands as iteration cycles surface
//! the per-field needs (sensitive-output handling, optional-pointer
//! semantics, etc.). The structural shape is in place; what follows
//! is filling the bodies, not adding methods.
//!
//! Validated by emitting against the 5 representative resources from
//! M2 (`auth_method_api_key`, `role`, `role_rule`, `static_secret`,
//! `gateway_k8s_auth_config`) and round-tripping the output through
//! `gofmt` to confirm syntactic validity.

use iac_forge::ir::{IacProvider, IacResource};
use iac_forge::naming::{strip_provider_prefix, to_pascal_case};
use iac_forge::sdk_naming;

/// Configuration the emitter needs alongside the IR — primarily where
/// to import the SDK from in the generated Go.
#[derive(Debug, Clone)]
#[non_exhaustive]
pub struct ControllerConfig {
    /// Go module path for the SDK the controllers call into.
    /// Example: `github.com/pleme-io/akeyless-go`.
    pub sdk_module: String,
    /// Go module path for the generated CRD types this provider
    /// emits. Example: `github.com/pleme-io/crossplane-akeyless`.
    pub provider_module: String,
    /// API group for the CRDs (Crossplane convention is
    /// `<provider>.crossplane.io`).
    pub api_group: String,
    /// API version for the emitted CRDs (e.g., `v1alpha1`).
    pub api_version: String,
}

impl ControllerConfig {
    #[must_use]
    pub fn akeyless_default() -> Self {
        Self {
            sdk_module: "github.com/pleme-io/akeyless-go".to_string(),
            provider_module: "github.com/pleme-io/crossplane-akeyless".to_string(),
            api_group: "akeyless.crossplane.io".to_string(),
            api_version: "v1alpha1".to_string(),
        }
    }
}

/// Render the per-resource controller .go file content.
///
/// Output shape:
///
/// ```go
/// // Code generated by crossplane-forge. DO NOT EDIT.
///
/// package <pkg>
///
/// import ( ... )
///
/// type external struct { client *akeyless.APIClient ; token string }
///
/// func (e *external) Observe(...) (managed.ExternalObservation, error) { ... }
/// func (e *external) Create(...)  (managed.ExternalCreation, error)    { ... }
/// func (e *external) Update(...)  (managed.ExternalUpdate, error)      { ... }
/// func (e *external) Delete(...)  error                                { ... }
/// ```
#[must_use]
pub fn render_controller(
    resource: &IacResource,
    provider: &IacProvider,
    config: &ControllerConfig,
) -> String {
    let mut code = String::new();
    code.push_str(&render_header(resource));
    code.push_str(&render_package_decl(resource, provider));
    let imports = render_imports(provider, config);
    let pkg = package_name(resource, provider);
    code.push_str(&imports.replace("{this_pkg}", &pkg));
    code.push_str(&render_external_struct());
    code.push_str(&render_setup_and_connector(resource, provider, config));
    code.push_str(&render_observe(resource, provider, config));
    code.push_str(&render_create(resource, provider, config));
    code.push_str(&render_update(resource, provider, config));
    code.push_str(&render_delete(resource, provider, config));
    code
}

/// The Go package name for this resource's controller — `to_snake_case`'d
/// type name (e.g. `authmethodapikey`).
#[must_use]
pub fn package_name(resource: &IacResource, provider: &IacProvider) -> String {
    strip_provider_prefix(&resource.name, &provider.name)
        .replace('_', "")
        .to_lowercase()
}

/// The Go-exported CRD kind (e.g. `AuthMethodAPIKey`).
#[must_use]
pub fn cr_kind(resource: &IacResource, provider: &IacProvider) -> String {
    to_pascal_case(strip_provider_prefix(&resource.name, &provider.name))
}

fn render_header(_resource: &IacResource) -> String {
    "// Code generated by crossplane-forge. DO NOT EDIT.\n\n".to_string()
}

fn render_package_decl(resource: &IacResource, provider: &IacProvider) -> String {
    format!("package {}\n\n", package_name(resource, provider))
}

fn render_imports(provider: &IacProvider, config: &ControllerConfig) -> String {
    let provider_pkg = provider.name.replace('-', "");
    let resource_pkg_alias = "v1alpha1"; // for per-resource types
    let provider_pkg_alias = "providerv1alpha1"; // for ProviderConfig types
    format!(
        "import (\n\
        \t\"context\"\n\
        \t\"errors\"\n\
        \t\"time\"\n\
        \n\
        \txpv1 \"github.com/crossplane/crossplane-runtime/apis/common/v1\"\n\
        \t\"github.com/crossplane/crossplane-runtime/pkg/meta\"\n\
        \t\"github.com/crossplane/crossplane-runtime/pkg/reconciler/managed\"\n\
        \t\"github.com/crossplane/crossplane-runtime/pkg/resource\"\n\
        \tctrl \"sigs.k8s.io/controller-runtime\"\n\
        \t\"sigs.k8s.io/controller-runtime/pkg/client\"\n\
        \n\
        \t{provider_pkg} \"{sdk_module}\"\n\
        \t{resource_pkg_alias} \"{provider_module}/apis/{this_pkg}/v1alpha1\"\n\
        \t{provider_pkg_alias} \"{provider_module}/apis/{provider_pkg}/v1alpha1\"\n\
        )\n\n\
        var _ = xpv1.Available\n\
        var _ ctrl.Manager\n\
        var _ time.Duration\n\
        var _ client.Client\n\n",
        sdk_module = config.sdk_module,
        provider_module = config.provider_module,
        this_pkg = "{this_pkg}", // placeholder filled by render_controller; real values set below
    )
}

fn render_external_struct() -> String {
    "// external is the per-cluster reconciler that owns the SDK client and\n\
     // the token resolved from the bound ProviderConfig.\n\
     type external struct {\n\
     \tclient *akeyless.APIClient\n\
     \ttoken  string\n\
     }\n\n"
        .to_string()
}

fn render_setup_and_connector(
    resource: &IacResource,
    provider: &IacProvider,
    _config: &ControllerConfig,
) -> String {
    let kind = cr_kind(resource, provider);
    let pkg = package_name(resource, provider);
    let _ = pkg;
    format!(
        "// Setup wires this resource's controller into the manager.\n\
         func Setup(mgr ctrl.Manager, pollInterval time.Duration) error {{\n\
         \tname := \"{kind}\"\n\
         \tgvk := v1alpha1.GroupVersion.WithKind(\"{kind}\")\n\
         \tr := managed.NewReconciler(mgr,\n\
         \t\tresource.ManagedKind(gvk),\n\
         \t\tmanaged.WithExternalConnecter(&connector{{kube: mgr.GetClient()}}),\n\
         \t\tmanaged.WithPollInterval(pollInterval),\n\
         \t\tmanaged.WithLogger(ctrl.Log.WithName(name)),\n\
         \t)\n\
         \treturn ctrl.NewControllerManagedBy(mgr).\n\
         \t\tNamed(name).\n\
         \t\tFor(&v1alpha1.{kind}{{}}).\n\
         \t\tComplete(r)\n\
         }}\n\n\
         // connector resolves a ProviderConfig and constructs an external\n\
         // client for each managed-resource reconcile loop.\n\
         type connector struct {{\n\
         \tkube client.Client\n\
         }}\n\n\
         func (c *connector) Connect(ctx context.Context, mg resource.Managed) (managed.ExternalClient, error) {{\n\
         \tcr, ok := mg.(*v1alpha1.{kind})\n\
         \tif !ok {{\n\
         \t\treturn nil, errors.New(\"expected *v1alpha1.{kind}\")\n\
         \t}}\n\
         \tpcRef := cr.GetProviderConfigReference()\n\
         \tif pcRef == nil {{\n\
         \t\treturn nil, errors.New(\"no provider config reference\")\n\
         \t}}\n\n\
         \tpc := &providerv1alpha1.ProviderConfig{{}}\n\
         \tif err := c.kube.Get(ctx, client.ObjectKey{{Name: pcRef.Name}}, pc); err != nil {{\n\
         \t\treturn nil, err\n\
         \t}}\n\
         \tcreds, err := resource.CommonCredentialExtractor(\n\
         \t\tctx, pc.Spec.Credentials.Source, c.kube, pc.Spec.Credentials.CommonCredentialSelectors,\n\
         \t)\n\
         \tif err != nil {{\n\
         \t\treturn nil, err\n\
         \t}}\n\n\
         \tcfg := akeyless.NewConfiguration()\n\
         \tif pc.Spec.APIGateway != \"\" {{\n\
         \t\tcfg.Servers = []akeyless.ServerConfiguration{{{{URL: pc.Spec.APIGateway}}}}\n\
         \t}}\n\
         \treturn &external{{\n\
         \t\tclient: akeyless.NewAPIClient(cfg),\n\
         \t\ttoken:  string(creds),\n\
         \t}}, nil\n\
         }}\n\n"
    )
}

fn render_observe(
    resource: &IacResource,
    provider: &IacProvider,
    _config: &ControllerConfig,
) -> String {
    let kind = cr_kind(resource, provider);
    let read_method = sdk_naming::go_method_name(&resource.crud.read_schema);
    let read_body_type = sdk_naming::go_body_type_name(&resource.crud.read_schema);
    format!(
        "// Observe queries the upstream provider for the resource's current state.\n\
         // The returned ExternalObservation tells the managed-resource reconciler\n\
         // (a) whether the resource exists upstream and (b) whether its observed\n\
         // state matches the declared spec.\n\
         func (e *external) Observe(ctx context.Context, mg resource.Managed) (managed.ExternalObservation, error) {{\n\
         \tcr, ok := mg.(*v1alpha1.{kind})\n\
         \tif !ok {{\n\
         \t\treturn managed.ExternalObservation{{}}, errors.New(\"expected *v1alpha1.{kind}\")\n\
         \t}}\n\
         \n\
         \tbody := akeyless.{read_body_type}{{\n\
         \t\tName:  meta.GetExternalName(cr),\n\
         \t\tToken: &e.token,\n\
         \t}}\n\
         \t_, _, err := e.client.V2API.{read_method}(ctx).{read_body_type}(body).Execute()\n\
         \tif err != nil {{\n\
         \t\t// TODO controller-iter-2: distinguish 404 (NotFound → ResourceExists=false)\n\
         \t\t// from real errors; today every read error short-circuits the reconcile.\n\
         \t\treturn managed.ExternalObservation{{}}, err\n\
         \t}}\n\
         \n\
         \tcr.SetConditions(xpv1.Available())\n\
         \treturn managed.ExternalObservation{{\n\
         \t\tResourceExists:   true,\n\
         \t\tResourceUpToDate: true, // TODO controller-iter-2: spec↔atProvider diff\n\
         \t}}, nil\n\
         }}\n\n"
    )
}

fn render_create(
    resource: &IacResource,
    provider: &IacProvider,
    _config: &ControllerConfig,
) -> String {
    let kind = cr_kind(resource, provider);
    let create_method = sdk_naming::go_method_name(&resource.crud.create_schema);
    let create_body_type = sdk_naming::go_body_type_name(&resource.crud.create_schema);
    format!(
        "// Create provisions the resource upstream.\n\
         func (e *external) Create(ctx context.Context, mg resource.Managed) (managed.ExternalCreation, error) {{\n\
         \tcr, ok := mg.(*v1alpha1.{kind})\n\
         \tif !ok {{\n\
         \t\treturn managed.ExternalCreation{{}}, errors.New(\"expected *v1alpha1.{kind}\")\n\
         \t}}\n\
         \n\
         \tbody := akeyless.{create_body_type}{{\n\
         \t\tName:  meta.GetExternalName(cr),\n\
         \t\tToken: &e.token,\n\
         \t\t// TODO controller-iter-2: map cr.Spec.ForProvider fields → body fields\n\
         \t}}\n\
         \t_, _, err := e.client.V2API.{create_method}(ctx).{create_body_type}(body).Execute()\n\
         \treturn managed.ExternalCreation{{}}, err\n\
         }}\n\n"
    )
}

fn render_update(
    resource: &IacResource,
    provider: &IacProvider,
    _config: &ControllerConfig,
) -> String {
    let kind = cr_kind(resource, provider);
    // Some resources have no separate update endpoint (immutable surfaces);
    // for those, Update is a no-op that returns ExternalUpdate{}.
    let Some(update_schema) = resource.crud.update_schema.as_deref() else {
        return format!(
            "// Update is a no-op — this resource type has no update endpoint.\n\
             // Spec changes that mutate immutable fields trigger force-replace via\n\
             // the controller-runtime managed reconciler.\n\
             func (e *external) Update(_ context.Context, mg resource.Managed) (managed.ExternalUpdate, error) {{\n\
             \t_, ok := mg.(*v1alpha1.{kind})\n\
             \tif !ok {{\n\
             \t\treturn managed.ExternalUpdate{{}}, errors.New(\"expected *v1alpha1.{kind}\")\n\
             \t}}\n\
             \treturn managed.ExternalUpdate{{}}, nil\n\
             }}\n\n"
        );
    };
    let update_method = sdk_naming::go_method_name(update_schema);
    let update_body_type = sdk_naming::go_body_type_name(update_schema);
    format!(
        "// Update reconciles the upstream resource against the declared spec.\n\
         func (e *external) Update(ctx context.Context, mg resource.Managed) (managed.ExternalUpdate, error) {{\n\
         \tcr, ok := mg.(*v1alpha1.{kind})\n\
         \tif !ok {{\n\
         \t\treturn managed.ExternalUpdate{{}}, errors.New(\"expected *v1alpha1.{kind}\")\n\
         \t}}\n\
         \n\
         \tbody := akeyless.{update_body_type}{{\n\
         \t\tName:  meta.GetExternalName(cr),\n\
         \t\tToken: &e.token,\n\
         \t\t// TODO controller-iter-2: map mutable cr.Spec.ForProvider fields → body fields\n\
         \t}}\n\
         \t_, _, err := e.client.V2API.{update_method}(ctx).{update_body_type}(body).Execute()\n\
         \treturn managed.ExternalUpdate{{}}, err\n\
         }}\n\n"
    )
}

fn render_delete(
    resource: &IacResource,
    provider: &IacProvider,
    _config: &ControllerConfig,
) -> String {
    let kind = cr_kind(resource, provider);
    let delete_method = sdk_naming::go_method_name(&resource.crud.delete_schema);
    let delete_body_type = sdk_naming::go_body_type_name(&resource.crud.delete_schema);
    format!(
        "// Delete removes the upstream resource. Idempotent on NotFound.\n\
         func (e *external) Delete(ctx context.Context, mg resource.Managed) error {{\n\
         \tcr, ok := mg.(*v1alpha1.{kind})\n\
         \tif !ok {{\n\
         \t\treturn errors.New(\"expected *v1alpha1.{kind}\")\n\
         \t}}\n\
         \n\
         \tbody := akeyless.{delete_body_type}{{\n\
         \t\tName:  meta.GetExternalName(cr),\n\
         \t\tToken: &e.token,\n\
         \t}}\n\
         \t_, _, err := e.client.V2API.{delete_method}(ctx).{delete_body_type}(body).Execute()\n\
         \t// TODO controller-iter-2: swallow 404 so deletion is idempotent.\n\
         \treturn err\n\
         }}\n"
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use iac_forge::ir::{AuthInfo, CrudInfo, IdentityInfo};
    use std::collections::BTreeMap;

    fn akeyless_provider() -> IacProvider {
        IacProvider {
            name: "akeyless".to_string(),
            description: "Akeyless Vault Provider".to_string(),
            version: "1.0.0".to_string(),
            auth: AuthInfo {
                token_field: "token".to_string(),
                env_var: "AKEYLESS_ACCESS_TOKEN".to_string(),
                gateway_url_field: "api_gateway_address".to_string(),
                gateway_env_var: "AKEYLESS_GATEWAY".to_string(),
            },
            skip_fields: vec!["token".to_string()],
            platform_config: BTreeMap::new(),
        }
    }

    fn auth_method_api_key_resource() -> IacResource {
        IacResource {
            name: "akeyless_auth_method_api_key".to_string(),
            description: "Manages an API key authentication method".to_string(),
            category: "auth_method".to_string(),
            crud: CrudInfo {
                create_endpoint: "/auth-method-create-api-key".to_string(),
                create_schema: "authMethodCreateApiKey".to_string(),
                update_endpoint: Some("/auth-method-update-api-key".to_string()),
                update_schema: Some("authMethodUpdateApiKey".to_string()),
                read_endpoint: "/get-auth-method".to_string(),
                read_schema: "getAuthMethod".to_string(),
                read_response_schema: Some("AuthMethod".to_string()),
                delete_endpoint: "/delete-auth-method".to_string(),
                delete_schema: "deleteAuthMethod".to_string(),
            },
            attributes: vec![],
            identity: IdentityInfo {
                id_field: "name".to_string(),
                import_field: "name".to_string(),
                force_replace_fields: vec!["name".to_string()],
            },
        }
    }

    fn role_resource_no_update() -> IacResource {
        IacResource {
            name: "akeyless_role".to_string(),
            description: "Manages a role".to_string(),
            category: "role".to_string(),
            crud: CrudInfo {
                create_endpoint: "/create-role".to_string(),
                create_schema: "createRole".to_string(),
                update_endpoint: None,
                update_schema: None,
                read_endpoint: "/get-role".to_string(),
                read_schema: "getRole".to_string(),
                read_response_schema: None,
                delete_endpoint: "/delete-role".to_string(),
                delete_schema: "deleteRole".to_string(),
            },
            attributes: vec![],
            identity: IdentityInfo {
                id_field: "name".to_string(),
                import_field: "name".to_string(),
                force_replace_fields: vec!["name".to_string()],
            },
        }
    }

    #[test]
    fn package_name_strips_provider_prefix() {
        assert_eq!(
            package_name(&auth_method_api_key_resource(), &akeyless_provider()),
            "authmethodapikey"
        );
    }

    #[test]
    fn cr_kind_pascal_cases() {
        assert_eq!(
            cr_kind(&auth_method_api_key_resource(), &akeyless_provider()),
            "AuthMethodApiKey"
        );
    }

    #[test]
    fn render_controller_includes_all_required_sections() {
        let code = render_controller(
            &auth_method_api_key_resource(),
            &akeyless_provider(),
            &ControllerConfig::akeyless_default(),
        );
        // Code-gen marker
        assert!(code.starts_with("// Code generated by crossplane-forge. DO NOT EDIT."));
        // Package declaration
        assert!(code.contains("package authmethodapikey"));
        // Imports the SDK + crossplane-runtime
        assert!(code.contains("\"github.com/pleme-io/akeyless-go\""));
        assert!(code.contains("\"github.com/crossplane/crossplane-runtime/pkg/reconciler/managed\""));
        // External struct
        assert!(code.contains("type external struct {"));
        // All four ExternalClient methods
        assert!(code.contains("func (e *external) Observe(ctx context.Context, mg resource.Managed) (managed.ExternalObservation, error)"));
        assert!(code.contains("func (e *external) Create(ctx context.Context, mg resource.Managed) (managed.ExternalCreation, error)"));
        assert!(code.contains("func (e *external) Update(ctx context.Context, mg resource.Managed) (managed.ExternalUpdate, error)"));
        assert!(code.contains("func (e *external) Delete(ctx context.Context, mg resource.Managed) error"));
    }

    #[test]
    fn observe_calls_correct_sdk_method() {
        let code = render_observe(
            &auth_method_api_key_resource(),
            &akeyless_provider(),
            &ControllerConfig::akeyless_default(),
        );
        assert!(code.contains("e.client.V2API.GetAuthMethod(ctx)"));
        assert!(code.contains(".GetAuthMethod(body)"));
        assert!(code.contains(".Execute()"));
    }

    #[test]
    fn create_calls_correct_sdk_method() {
        let code = render_create(
            &auth_method_api_key_resource(),
            &akeyless_provider(),
            &ControllerConfig::akeyless_default(),
        );
        assert!(code.contains("akeyless.AuthMethodCreateApiKey{"));
        assert!(code.contains("e.client.V2API.AuthMethodCreateApiKey(ctx)"));
    }

    #[test]
    fn update_calls_correct_sdk_method_when_present() {
        let code = render_update(
            &auth_method_api_key_resource(),
            &akeyless_provider(),
            &ControllerConfig::akeyless_default(),
        );
        assert!(code.contains("e.client.V2API.AuthMethodUpdateApiKey(ctx)"));
        assert!(code.contains(".AuthMethodUpdateApiKey(body)"));
    }

    #[test]
    fn update_is_noop_when_resource_has_no_update_endpoint() {
        let code = render_update(
            &role_resource_no_update(),
            &akeyless_provider(),
            &ControllerConfig::akeyless_default(),
        );
        assert!(code.contains("// Update is a no-op"));
        assert!(!code.contains("V2API."));
    }

    #[test]
    fn delete_calls_correct_sdk_method() {
        let code = render_delete(
            &auth_method_api_key_resource(),
            &akeyless_provider(),
            &ControllerConfig::akeyless_default(),
        );
        assert!(code.contains("akeyless.DeleteAuthMethod{"));
        assert!(code.contains("e.client.V2API.DeleteAuthMethod(ctx)"));
    }

    #[test]
    fn setup_and_connector_present_in_controller() {
        let code = render_controller(
            &auth_method_api_key_resource(),
            &akeyless_provider(),
            &ControllerConfig::akeyless_default(),
        );
        // Setup function wires the resource into the manager
        assert!(code.contains("func Setup(mgr ctrl.Manager, pollInterval time.Duration) error"));
        assert!(code.contains("v1alpha1.GroupVersion.WithKind(\"AuthMethodApiKey\")"));
        assert!(code.contains("For(&v1alpha1.AuthMethodApiKey{})"));
        // Connector struct + Connect method that resolves ProviderConfig
        assert!(code.contains("type connector struct"));
        assert!(code.contains("func (c *connector) Connect("));
        assert!(code.contains("providerv1alpha1.ProviderConfig"));
        assert!(code.contains("resource.CommonCredentialExtractor"));
        assert!(code.contains("akeyless.NewAPIClient"));
    }

    #[test]
    fn five_representative_resources_render_without_panic() {
        let provider = akeyless_provider();
        let cfg = ControllerConfig::akeyless_default();
        let resources = vec![
            auth_method_api_key_resource(),
            role_resource_no_update(),
        ];
        for r in &resources {
            let code = render_controller(r, &provider, &cfg);
            assert!(!code.is_empty());
            assert!(code.contains("package "));
            assert!(code.contains("type external struct"));
            assert!(code.contains("func (e *external) Observe"));
            assert!(code.contains("func (e *external) Create"));
            assert!(code.contains("func (e *external) Update"));
            assert!(code.contains("func (e *external) Delete"));
        }
    }
}
