//! Provider-runtime scaffold emitter.
//!
//! Where `types_gen` + `controller_gen` emit per-resource artifacts,
//! this module emits the cross-cutting scaffold that wraps them into a
//! buildable, deployable Crossplane provider:
//!
//!   apis/<provider>/v1alpha1/providerconfig_types.go    ← cred plug
//!   apis/<provider>/v1alpha1/groupversion_info.go       ← scheme glue
//!   apis/<provider>/v1alpha1/zz_register.go             ← registers all kinds
//!   cmd/provider/main.go                                ← entry point
//!   internal/controller/setup.go                        ← controller wiring
//!   go.mod                                              ← Go module manifest
//!   helm/Chart.yaml + helm/values.yaml + helm/templates/* ← deployment
//!
//! ## Status (slice 1)
//!
//! Emits the structural shape correctly. The Helm chart emission is
//! minimum-viable (single Deployment + ServiceAccount + ClusterRole +
//! ClusterRoleBinding + ProviderConfig kinds). Slice 2 adds NetworkPolicy,
//! ServiceMonitor, leader-election RBAC tightening, and per-controller
//! resource limits.

use iac_forge::ir::{IacProvider, IacResource};

use crate::controller_gen::{ControllerConfig, package_name};

/// Render `apis/<provider>/v1alpha1/providerconfig_types.go` — the
/// `ProviderConfig` + `ProviderConfigUsage` types every Crossplane
/// provider ships.
#[must_use]
pub fn render_provider_config_types(provider: &IacProvider, _config: &ControllerConfig) -> String {
    let provider_pkg = provider.name.replace('-', "");
    let _ = provider_pkg; // kept for future usage in the api docs
    "// Code generated by crossplane-forge. DO NOT EDIT.\n\
\n\
package v1alpha1\n\
\n\
import (\n\
\tmetav1 \"k8s.io/apimachinery/pkg/apis/meta/v1\"\n\
\n\
\txpv1 \"github.com/crossplane/crossplane-runtime/apis/common/v1\"\n\
)\n\
\n\
// ProviderConfigSpec defines the desired state of a ProviderConfig.\n\
type ProviderConfigSpec struct {\n\
\t// Credentials required to authenticate to the upstream API.\n\
\t// +kubebuilder:validation:Required\n\
\tCredentials ProviderCredentials `json:\"credentials\"`\n\
\n\
\t// APIGateway is the URL of the API endpoint to call.\n\
\t// +optional\n\
\tAPIGateway string `json:\"apiGateway,omitempty\"`\n\
}\n\
\n\
// ProviderCredentials carries the credential source + selector.\n\
type ProviderCredentials struct {\n\
\t// Source of the provider credentials.\n\
\t// +kubebuilder:validation:Enum=None;Secret;Environment;Filesystem\n\
\t// +kubebuilder:validation:Required\n\
\tSource xpv1.CredentialsSource `json:\"source\"`\n\
\n\
\txpv1.CommonCredentialSelectors `json:\",inline\"`\n\
}\n\
\n\
// +kubebuilder:object:root=true\n\
// +kubebuilder:subresource:status\n\
// +kubebuilder:resource:scope=Cluster,categories={crossplane,provider,akeyless}\n\
// +kubebuilder:printcolumn:name=\"AGE\",type=\"date\",JSONPath=\".metadata.creationTimestamp\"\n\
// +kubebuilder:printcolumn:name=\"SECRET-NAME\",type=\"string\",JSONPath=\".spec.credentials.secretRef.name\",priority=1\n\
type ProviderConfig struct {\n\
\tmetav1.TypeMeta   `json:\",inline\"`\n\
\tmetav1.ObjectMeta `json:\"metadata,omitempty\"`\n\
\n\
\tSpec   ProviderConfigSpec        `json:\"spec\"`\n\
\tStatus xpv1.ProviderConfigStatus `json:\"status,omitempty\"`\n\
}\n\
\n\
// +kubebuilder:object:root=true\n\
type ProviderConfigList struct {\n\
\tmetav1.TypeMeta `json:\",inline\"`\n\
\tmetav1.ListMeta `json:\"metadata,omitempty\"`\n\
\tItems           []ProviderConfig `json:\"items\"`\n\
}\n\
\n\
// +kubebuilder:object:root=true\n\
// +kubebuilder:subresource:status\n\
// +kubebuilder:resource:scope=Cluster,categories={crossplane,provider,akeyless}\n\
// +kubebuilder:printcolumn:name=\"CONFIG-NAME\",type=\"string\",JSONPath=\".providerConfigRef.name\"\n\
// +kubebuilder:printcolumn:name=\"RESOURCE-KIND\",type=\"string\",JSONPath=\".resourceRef.kind\"\n\
// +kubebuilder:printcolumn:name=\"RESOURCE-NAME\",type=\"string\",JSONPath=\".resourceRef.name\"\n\
type ProviderConfigUsage struct {\n\
\tmetav1.TypeMeta   `json:\",inline\"`\n\
\tmetav1.ObjectMeta `json:\"metadata,omitempty\"`\n\
\n\
\txpv1.ProviderConfigUsage `json:\",inline\"`\n\
}\n\
\n\
// +kubebuilder:object:root=true\n\
type ProviderConfigUsageList struct {\n\
\tmetav1.TypeMeta `json:\",inline\"`\n\
\tmetav1.ListMeta `json:\"metadata,omitempty\"`\n\
\tItems           []ProviderConfigUsage `json:\"items\"`\n\
}\n".to_string()
}

/// Render `apis/<provider>/v1alpha1/groupversion_info.go` for the provider's
/// root API group (where ProviderConfig + ProviderConfigUsage live).
#[must_use]
pub fn render_provider_groupversion_info(provider: &IacProvider, config: &ControllerConfig) -> String {
    let _ = provider;
    format!(
        "// Code generated by crossplane-forge. DO NOT EDIT.\n\
\n\
// +kubebuilder:object:generate=true\n\
// +groupName={api_group}\n\
package v1alpha1\n\
\n\
import (\n\
\t\"k8s.io/apimachinery/pkg/runtime/schema\"\n\
\t\"sigs.k8s.io/controller-runtime/pkg/scheme\"\n\
)\n\
\n\
var (\n\
\tGroupVersion = schema.GroupVersion{{Group: \"{api_group}\", Version: \"{api_version}\"}}\n\
\tSchemeBuilder = &scheme.Builder{{GroupVersion: GroupVersion}}\n\
\tAddToScheme = SchemeBuilder.AddToScheme\n\
)\n\
\n\
func init() {{\n\
\tSchemeBuilder.Register(\n\
\t\t&ProviderConfig{{}}, &ProviderConfigList{{}},\n\
\t\t&ProviderConfigUsage{{}}, &ProviderConfigUsageList{{}},\n\
\t)\n\
}}\n",
        api_group = config.api_group,
        api_version = config.api_version,
    )
}

/// Render `cmd/provider/main.go` — the provider entry point.
#[must_use]
pub fn render_main_go(_provider: &IacProvider, config: &ControllerConfig) -> String {
    format!(
        "// Code generated by crossplane-forge. DO NOT EDIT.\n\
\n\
package main\n\
\n\
import (\n\
\t\"flag\"\n\
\t\"fmt\"\n\
\t\"os\"\n\
\t\"time\"\n\
\n\
\tctrl \"sigs.k8s.io/controller-runtime\"\n\
\t\"sigs.k8s.io/controller-runtime/pkg/log/zap\"\n\
\n\
\tapis \"{provider_module}/apis\"\n\
\t\"{provider_module}/internal/controller\"\n\
)\n\
\n\
func main() {{\n\
\tvar (\n\
\t\tleaderElection bool\n\
\t\tpollInterval   time.Duration\n\
\t)\n\
\tflag.BoolVar(&leaderElection, \"leader-election\", false, \"Enable leader election for the controller manager.\")\n\
\tflag.DurationVar(&pollInterval, \"poll\", time.Minute, \"Poll interval for managed-resource reconciliation.\")\n\
\tflag.Parse()\n\
\n\
\tctrl.SetLogger(zap.New(zap.UseDevMode(true)))\n\
\n\
\tcfg, err := ctrl.GetConfig()\n\
\tif err != nil {{\n\
\t\tfmt.Fprintln(os.Stderr, \"GetConfig:\", err)\n\
\t\tos.Exit(1)\n\
\t}}\n\
\n\
\tmgr, err := ctrl.NewManager(cfg, ctrl.Options{{\n\
\t\tLeaderElection:   leaderElection,\n\
\t\tLeaderElectionID: \"crossplane-{provider_name}-leader\",\n\
\t}})\n\
\tif err != nil {{\n\
\t\tfmt.Fprintln(os.Stderr, \"NewManager:\", err)\n\
\t\tos.Exit(1)\n\
\t}}\n\
\n\
\tif err := apis.AddToScheme(mgr.GetScheme()); err != nil {{\n\
\t\tfmt.Fprintln(os.Stderr, \"AddToScheme:\", err)\n\
\t\tos.Exit(1)\n\
\t}}\n\
\n\
\tif err := controller.Setup(mgr, pollInterval); err != nil {{\n\
\t\tfmt.Fprintln(os.Stderr, \"controller.Setup:\", err)\n\
\t\tos.Exit(1)\n\
\t}}\n\
\n\
\tif err := mgr.Start(ctrl.SetupSignalHandler()); err != nil {{\n\
\t\tfmt.Fprintln(os.Stderr, \"mgr.Start:\", err)\n\
\t\tos.Exit(1)\n\
\t}}\n\
}}\n",
        provider_module = config.provider_module,
        provider_name = _provider.name,
    )
}

/// Render `internal/controller/setup.go` — wires every per-resource
/// controller into the manager.
#[must_use]
pub fn render_setup_go(
    resources: &[IacResource],
    provider: &IacProvider,
    config: &ControllerConfig,
) -> String {
    let mut imports = String::new();
    let mut calls = String::new();
    for r in resources {
        let pkg = package_name(r, provider);
        imports.push_str(&format!(
            "\t\"{module}/internal/controller/{pkg}\"\n",
            module = config.provider_module,
        ));
        calls.push_str(&format!("\t\t{pkg}.Setup,\n"));
    }
    format!(
        "// Code generated by crossplane-forge. DO NOT EDIT.\n\
\n\
package controller\n\
\n\
import (\n\
\t\"time\"\n\
\n\
\tctrl \"sigs.k8s.io/controller-runtime\"\n\
\n\
{imports})\n\
\n\
// Setup wires every resource controller into the manager. Returns the\n\
// first error encountered; nil on success.\n\
func Setup(mgr ctrl.Manager, pollInterval time.Duration) error {{\n\
\tsetups := []func(ctrl.Manager, time.Duration) error{{\n\
{calls}\t}}\n\
\tfor _, s := range setups {{\n\
\t\tif err := s(mgr, pollInterval); err != nil {{\n\
\t\t\treturn err\n\
\t\t}}\n\
\t}}\n\
\treturn nil\n\
}}\n"
    )
}

/// Render the provider's `go.mod` file with the runtime deps.
#[must_use]
pub fn render_go_mod(_provider: &IacProvider, config: &ControllerConfig) -> String {
    format!(
        "module {provider_module}\n\
\n\
go 1.23\n\
\n\
require (\n\
\t{sdk_module} v0.1.0\n\
\tgithub.com/crossplane/crossplane-runtime v1.18.0\n\
\tk8s.io/apimachinery v0.31.0\n\
\tsigs.k8s.io/controller-runtime v0.19.0\n\
)\n",
        provider_module = config.provider_module,
        sdk_module = config.sdk_module,
    )
}

/// Render the Helm chart's `Chart.yaml`.
#[must_use]
pub fn render_helm_chart_yaml(provider: &IacProvider, config: &ControllerConfig) -> String {
    let _ = config;
    format!(
        "apiVersion: v2\n\
name: crossplane-{provider_name}\n\
description: Crossplane provider for {provider_name}\n\
type: application\n\
version: 0.1.0\n\
appVersion: \"0.1.0\"\n\
keywords:\n\
\t- crossplane\n\
\t- provider\n\
\t- {provider_name}\n",
        provider_name = provider.name,
    )
}

/// Render the Helm chart's `values.yaml`.
#[must_use]
pub fn render_helm_values_yaml(provider: &IacProvider, _config: &ControllerConfig) -> String {
    format!(
        "image:\n\
\trepository: ghcr.io/pleme-io/crossplane-{provider_name}\n\
\ttag: \"\"  # defaults to chart appVersion\n\
\tpullPolicy: IfNotPresent\n\
\n\
replicas: 1\n\
\n\
serviceAccount:\n\
\tcreate: true\n\
\tname: \"\"\n\
\n\
resources:\n\
\trequests:\n\
\t\tcpu: 100m\n\
\t\tmemory: 128Mi\n\
\tlimits:\n\
\t\tcpu: 500m\n\
\t\tmemory: 512Mi\n\
\n\
leaderElection:\n\
\tenabled: true\n\
\n\
pollInterval: 60s\n",
        provider_name = provider.name,
    )
}

/// Render the Helm Deployment template.
#[must_use]
pub fn render_helm_deployment_template(provider: &IacProvider, _config: &ControllerConfig) -> String {
    let n = &provider.name;
    let _ = n;
    "apiVersion: apps/v1\n\
kind: Deployment\n\
metadata:\n\
  name: {{ include \"crossplane-{{ .Values.provider }}.fullname\" . | default (printf \"crossplane-%s\" .Chart.Name) }}\n\
  labels:\n\
    app.kubernetes.io/name: {{ .Chart.Name }}\n\
    app.kubernetes.io/managed-by: {{ .Release.Service }}\n\
spec:\n\
  replicas: {{ .Values.replicas }}\n\
  selector:\n\
    matchLabels:\n\
      app.kubernetes.io/name: {{ .Chart.Name }}\n\
  template:\n\
    metadata:\n\
      labels:\n\
        app.kubernetes.io/name: {{ .Chart.Name }}\n\
    spec:\n\
      serviceAccountName: {{ .Values.serviceAccount.name | default (printf \"crossplane-%s\" .Chart.Name) }}\n\
      containers:\n\
        - name: provider\n\
          image: \"{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}\"\n\
          imagePullPolicy: {{ .Values.image.pullPolicy }}\n\
          args:\n\
            - --leader-election={{ .Values.leaderElection.enabled }}\n\
            - --poll={{ .Values.pollInterval }}\n\
          resources:\n\
{{ toYaml .Values.resources | indent 12 }}\n".to_string()
}

/// Render Helm RBAC template (ClusterRole + ClusterRoleBinding +
/// ServiceAccount).
#[must_use]
pub fn render_helm_rbac_template(_provider: &IacProvider, _config: &ControllerConfig) -> String {
    "{{- if .Values.serviceAccount.create }}\n\
apiVersion: v1\n\
kind: ServiceAccount\n\
metadata:\n\
  name: {{ .Values.serviceAccount.name | default (printf \"crossplane-%s\" .Chart.Name) }}\n\
{{- end }}\n\
---\n\
apiVersion: rbac.authorization.k8s.io/v1\n\
kind: ClusterRole\n\
metadata:\n\
  name: crossplane-{{ .Chart.Name }}\n\
rules:\n\
  - apiGroups: [\"\"]\n\
    resources: [\"events\", \"secrets\"]\n\
    verbs: [\"get\", \"list\", \"watch\", \"create\", \"update\", \"patch\"]\n\
  - apiGroups: [\"coordination.k8s.io\"]\n\
    resources: [\"leases\"]\n\
    verbs: [\"get\", \"list\", \"watch\", \"create\", \"update\", \"patch\", \"delete\"]\n\
  # Crossplane's own kinds — managed-resource reconciler patterns require\n\
  # full access to the provider's CRDs. Tightened in slice 2.\n\
  - apiGroups: [\"akeyless.crossplane.io\", \"*.akeyless.crossplane.io\"]\n\
    resources: [\"*\"]\n\
    verbs: [\"get\", \"list\", \"watch\", \"create\", \"update\", \"patch\", \"delete\"]\n\
  - apiGroups: [\"akeyless.crossplane.io\", \"*.akeyless.crossplane.io\"]\n\
    resources: [\"*/status\", \"*/finalizers\"]\n\
    verbs: [\"get\", \"update\", \"patch\"]\n\
---\n\
apiVersion: rbac.authorization.k8s.io/v1\n\
kind: ClusterRoleBinding\n\
metadata:\n\
  name: crossplane-{{ .Chart.Name }}\n\
roleRef:\n\
  apiGroup: rbac.authorization.k8s.io\n\
  kind: ClusterRole\n\
  name: crossplane-{{ .Chart.Name }}\n\
subjects:\n\
  - kind: ServiceAccount\n\
    name: {{ .Values.serviceAccount.name | default (printf \"crossplane-%s\" .Chart.Name) }}\n\
    namespace: {{ .Release.Namespace }}\n".to_string()
}

#[cfg(test)]
mod tests {
    use super::*;
    use iac_forge::ir::{AuthInfo, CrudInfo, IdentityInfo};
    use std::collections::BTreeMap;

    fn provider() -> IacProvider {
        IacProvider {
            name: "akeyless".to_string(),
            description: String::new(),
            version: "1.0.0".to_string(),
            auth: AuthInfo::default(),
            skip_fields: vec![],
            platform_config: BTreeMap::new(),
        }
    }

    fn auth_method() -> IacResource {
        IacResource {
            name: "akeyless_auth_method_api_key".to_string(),
            description: String::new(),
            category: "auth_method".to_string(),
            crud: CrudInfo {
                create_endpoint: "/x".to_string(),
                create_schema: "x".to_string(),
                update_endpoint: None,
                update_schema: None,
                read_endpoint: "/y".to_string(),
                read_schema: "y".to_string(),
                read_response_schema: None,
                delete_endpoint: "/z".to_string(),
                delete_schema: "z".to_string(),
            },
            attributes: vec![],
            identity: IdentityInfo {
                id_field: "name".to_string(),
                import_field: "name".to_string(),
                force_replace_fields: vec![],
            },
        }
    }

    #[test]
    fn provider_config_has_all_required_kinds() {
        let code = render_provider_config_types(&provider(), &ControllerConfig::akeyless_default());
        assert!(code.contains("type ProviderConfig struct"));
        assert!(code.contains("type ProviderConfigList struct"));
        assert!(code.contains("type ProviderConfigUsage struct"));
        assert!(code.contains("type ProviderConfigUsageList struct"));
        assert!(code.contains("type ProviderCredentials struct"));
        assert!(code.contains("xpv1.ProviderConfigStatus"));
        assert!(code.contains("xpv1.CommonCredentialSelectors"));
    }

    #[test]
    fn provider_groupversion_info_registers_all_4_kinds() {
        let code = render_provider_groupversion_info(&provider(), &ControllerConfig::akeyless_default());
        assert!(code.contains("&ProviderConfig{}"));
        assert!(code.contains("&ProviderConfigList{}"));
        assert!(code.contains("&ProviderConfigUsage{}"));
        assert!(code.contains("&ProviderConfigUsageList{}"));
        assert!(code.contains("Group: \"akeyless.crossplane.io\""));
    }

    #[test]
    fn main_go_imports_apis_and_controller() {
        let code = render_main_go(&provider(), &ControllerConfig::akeyless_default());
        assert!(code.contains("package main"));
        assert!(code.contains("github.com/pleme-io/crossplane-akeyless/apis"));
        assert!(code.contains("github.com/pleme-io/crossplane-akeyless/internal/controller"));
        assert!(code.contains("apis.AddToScheme"));
        assert!(code.contains("controller.Setup"));
        assert!(code.contains("LeaderElectionID: \"crossplane-akeyless-leader\""));
    }

    #[test]
    fn setup_go_imports_each_resource_package_and_calls_its_setup() {
        let code = render_setup_go(
            &[auth_method()],
            &provider(),
            &ControllerConfig::akeyless_default(),
        );
        assert!(code.contains("package controller"));
        assert!(code.contains("\"github.com/pleme-io/crossplane-akeyless/internal/controller/authmethodapikey\""));
        assert!(code.contains("authmethodapikey.Setup,"));
    }

    #[test]
    fn go_mod_pins_runtime_deps() {
        let code = render_go_mod(&provider(), &ControllerConfig::akeyless_default());
        assert!(code.contains("module github.com/pleme-io/crossplane-akeyless"));
        assert!(code.contains("github.com/pleme-io/akeyless-go v0.1.0"));
        assert!(code.contains("github.com/crossplane/crossplane-runtime"));
        assert!(code.contains("sigs.k8s.io/controller-runtime"));
    }

    #[test]
    fn helm_chart_metadata_uses_provider_name() {
        let code = render_helm_chart_yaml(&provider(), &ControllerConfig::akeyless_default());
        assert!(code.contains("name: crossplane-akeyless"));
        assert!(code.contains("apiVersion: v2"));
    }

    #[test]
    fn helm_values_default_image_repository() {
        let code = render_helm_values_yaml(&provider(), &ControllerConfig::akeyless_default());
        assert!(code.contains("ghcr.io/pleme-io/crossplane-akeyless"));
        assert!(code.contains("leaderElection:"));
    }

    #[test]
    fn helm_deployment_uses_chart_appversion() {
        let code = render_helm_deployment_template(&provider(), &ControllerConfig::akeyless_default());
        assert!(code.contains("kind: Deployment"));
        assert!(code.contains(".Chart.AppVersion"));
        assert!(code.contains("--leader-election"));
    }

    #[test]
    fn helm_rbac_includes_serviceaccount_clusterrole_binding() {
        let code = render_helm_rbac_template(&provider(), &ControllerConfig::akeyless_default());
        assert!(code.contains("kind: ServiceAccount"));
        assert!(code.contains("kind: ClusterRole"));
        assert!(code.contains("kind: ClusterRoleBinding"));
    }
}
