//! Crossplane-managed-resource Go-types emitter.
//!
//! For each `IacResource`, produces a `<resource>_types.go` file inside
//! `apis/<package>/v1alpha1/` containing the Go structs the Crossplane
//! reconciler binds to: `<Kind>Parameters`, `<Kind>Observation`,
//! `<Kind>Spec` (with `xpv1.ResourceSpec` embedded), `<Kind>Status` (with
//! `xpv1.ResourceStatus` embedded), the `<Kind>` managed-resource type
//! itself, and the `<Kind>List` plural.
//!
//! Plus a single `groupversion_info.go` per Go package, providing the
//! `SchemeBuilder` glue that controller-runtime needs to register the
//! types into the API scheme.
//!
//! ## Status (slice 1)
//!
//! Emits the structural shape correctly (every Crossplane managed-
//! resource convention satisfied) with attribute fields rendered as
//! `string` regardless of the IR `IacType` — full type mapping
//! (`Integer` → `*int64`, optional → `*T`, `Map` → `map[string]string`,
//! etc.) lands in slice 2 once the first resource is round-tripping
//! end-to-end through `go build`. The tradeoff is intentional: get the
//! pipeline green for one resource, then expand the type-mapping
//! coverage. The kubebuilder tag generation is complete in slice 1.

use iac_forge::ir::{IacAttribute, IacProvider, IacResource, IacType};
use iac_forge::naming::{strip_provider_prefix, to_pascal_case, to_snake_case};

use crate::controller_gen::{cr_kind, package_name};

/// Render the per-resource `<resource>_types.go` content (the Spec /
/// Status / Parameters / Observation / Kind / KindList structs).
#[must_use]
pub fn render_resource_types(resource: &IacResource, provider: &IacProvider) -> String {
    let kind = cr_kind(resource, provider);
    let mut code = String::new();
    code.push_str("// Code generated by crossplane-forge. DO NOT EDIT.\n\n");
    code.push_str("package v1alpha1\n\n");
    code.push_str(
        "import (\n\
         \tmetav1 \"k8s.io/apimachinery/pkg/apis/meta/v1\"\n\
         \n\
         \txpv1 \"github.com/crossplane/crossplane-runtime/apis/common/v1\"\n\
         )\n\n",
    );
    code.push_str(&render_parameters(resource, &kind));
    code.push_str(&render_observation(resource, &kind));
    code.push_str(&render_spec(&kind));
    code.push_str(&render_status(&kind));
    code.push_str(&render_kind(resource, provider, &kind));
    code.push_str(&render_kind_list(&kind));
    code
}

/// Render the package-level `groupversion_info.go`. Once per emitted
/// package (one package per resource in slice 1; we collapse to per-
/// category packages in slice 2).
#[must_use]
pub fn render_groupversion_info(
    resource: &IacResource,
    provider: &IacProvider,
    api_group_for_package: &str,
    api_version: &str,
) -> String {
    let kind = cr_kind(resource, provider);
    format!(
        "// Code generated by crossplane-forge. DO NOT EDIT.\n\n\
         // +kubebuilder:object:generate=true\n\
         // +groupName={api_group}\n\
         package v1alpha1\n\n\
         import (\n\
         \t\"k8s.io/apimachinery/pkg/runtime/schema\"\n\
         \t\"sigs.k8s.io/controller-runtime/pkg/scheme\"\n\
         )\n\n\
         var (\n\
         \tGroupVersion = schema.GroupVersion{{Group: \"{api_group}\", Version: \"{api_version}\"}}\n\
         \tSchemeBuilder = &scheme.Builder{{GroupVersion: GroupVersion}}\n\
         \tAddToScheme = SchemeBuilder.AddToScheme\n\
         )\n\n\
         func init() {{\n\
         \tSchemeBuilder.Register(&{kind}{{}}, &{kind}List{{}})\n\
         }}\n",
        api_group = api_group_for_package,
    )
}

fn render_parameters(resource: &IacResource, kind: &str) -> String {
    let fields = resource
        .attributes
        .iter()
        .filter(|a| !a.computed)
        .map(render_field)
        .collect::<Vec<_>>()
        .join("");
    format!(
        "// {kind}Parameters defines the desired state of the resource.\n\
         type {kind}Parameters struct {{\n{fields}}}\n\n"
    )
}

fn render_observation(resource: &IacResource, kind: &str) -> String {
    let fields = resource
        .attributes
        .iter()
        .filter(|a| a.computed)
        .map(render_field)
        .collect::<Vec<_>>()
        .join("");
    format!(
        "// {kind}Observation reflects the observed state from the upstream provider.\n\
         type {kind}Observation struct {{\n{fields}}}\n\n"
    )
}

fn render_field(attr: &IacAttribute) -> String {
    let go_field_name = to_pascal_case(&to_snake_case(&attr.canonical_name));
    let go_type = iac_type_to_go(&attr.iac_type, attr.required);
    let json_tag = if attr.required {
        attr.canonical_name.clone()
    } else {
        format!("{},omitempty", attr.canonical_name)
    };
    let mut tags = vec![format!("json:\"{json_tag}\"")];
    if attr.required {
        tags.insert(0, "// +kubebuilder:validation:Required".to_string());
    }
    let kubebuilder_required = if attr.required {
        "\t// +kubebuilder:validation:Required\n"
    } else {
        ""
    };
    let immutability = if attr.immutable {
        "\t// +kubebuilder:validation:XValidation:rule=\"self == oldSelf\",message=\"field is immutable\"\n"
    } else {
        ""
    };
    let description_comment = if attr.description.is_empty() {
        String::new()
    } else {
        format!("\t// {}\n", attr.description.replace('\n', " "))
    };
    let _ = tags; // silence pedantic about-to-be-merged var
    format!(
        "{description_comment}{kubebuilder_required}{immutability}\t{go_field_name} {go_type} `json:\"{json_tag}\"`\n"
    )
}

fn iac_type_to_go(t: &IacType, required: bool) -> String {
    let base = match t {
        IacType::String => "string",
        IacType::Integer => "int64",
        IacType::Float => "float64",
        IacType::Numeric => "float64",
        IacType::Boolean => "bool",
        // Collections + complex types collapse to opaque strings in slice 1
        // — the field-level type mapping graduates in slice 2 when the
        // first resource is round-tripping end-to-end through `go build`.
        IacType::List(_)
        | IacType::Set(_)
        | IacType::Map(_)
        | IacType::Object { .. }
        | IacType::Enum { .. }
        | IacType::Any => "string",
        _ => "string",
    };
    if required {
        base.to_string()
    } else {
        format!("*{base}")
    }
}

fn render_spec(kind: &str) -> String {
    format!(
        "// {kind}Spec is the desired state of the resource.\n\
         type {kind}Spec struct {{\n\
         \txpv1.ResourceSpec `json:\",inline\"`\n\
         \tForProvider {kind}Parameters `json:\"forProvider\"`\n\
         }}\n\n"
    )
}

fn render_status(kind: &str) -> String {
    format!(
        "// {kind}Status reflects the observed state of the resource.\n\
         type {kind}Status struct {{\n\
         \txpv1.ResourceStatus `json:\",inline\"`\n\
         \tAtProvider {kind}Observation `json:\"atProvider,omitempty\"`\n\
         }}\n\n"
    )
}

fn render_kind(resource: &IacResource, provider: &IacProvider, kind: &str) -> String {
    // Plural form: append "s" to the kind. For correct pluralization
    // edge cases ("y" → "ies", "s" → "ses") we'd want a real
    // pluralizer, but kubebuilder is lenient about printer columns
    // referencing them by plural — slice 2 uses meimei or similar.
    let _ = resource;
    let _ = provider;
    format!(
        "// +kubebuilder:object:root=true\n\
         // +kubebuilder:subresource:status\n\
         // +kubebuilder:resource:scope=Cluster,categories={{crossplane,akeyless,managed}}\n\
         // +kubebuilder:printcolumn:name=\"READY\",type=\"string\",JSONPath=\".status.conditions[?(@.type=='Ready')].status\"\n\
         // +kubebuilder:printcolumn:name=\"SYNCED\",type=\"string\",JSONPath=\".status.conditions[?(@.type=='Synced')].status\"\n\
         // +kubebuilder:printcolumn:name=\"EXTERNAL-NAME\",type=\"string\",JSONPath=\".metadata.annotations['crossplane\\\\.io/external-name']\"\n\
         // +kubebuilder:printcolumn:name=\"AGE\",type=\"date\",JSONPath=\".metadata.creationTimestamp\"\n\
         type {kind} struct {{\n\
         \tmetav1.TypeMeta   `json:\",inline\"`\n\
         \tmetav1.ObjectMeta `json:\"metadata,omitempty\"`\n\
         \n\
         \tSpec   {kind}Spec   `json:\"spec\"`\n\
         \tStatus {kind}Status `json:\"status,omitempty\"`\n\
         }}\n\n"
    )
}

fn render_kind_list(kind: &str) -> String {
    format!(
        "// +kubebuilder:object:root=true\n\
         type {kind}List struct {{\n\
         \tmetav1.TypeMeta `json:\",inline\"`\n\
         \tmetav1.ListMeta `json:\"metadata,omitempty\"`\n\
         \tItems []{kind} `json:\"items\"`\n\
         }}\n"
    )
}

/// Naming helper: which Go package does this resource's types belong to?
/// Slice 1 collapses every resource into a single per-resource package
/// (named after the resource's snake-stripped kind). Slice 2 collapses
/// resources by category.
#[must_use]
pub fn types_package_name(resource: &IacResource, provider: &IacProvider) -> String {
    package_name(resource, provider)
}

/// Path the types_gen output should land at: `apis/<pkg>/v1alpha1/types.go`.
#[must_use]
pub fn types_file_path(resource: &IacResource, provider: &IacProvider) -> String {
    let pkg = types_package_name(resource, provider);
    format!("apis/{pkg}/v1alpha1/{}_types.go", to_snake_case(&strip_provider_prefix(&resource.name, &provider.name)))
}

/// Path the groupversion_info output should land at:
/// `apis/<pkg>/v1alpha1/groupversion_info.go`.
#[must_use]
pub fn groupversion_file_path(resource: &IacResource, provider: &IacProvider) -> String {
    let pkg = types_package_name(resource, provider);
    format!("apis/{pkg}/v1alpha1/groupversion_info.go")
}

#[cfg(test)]
mod tests {
    use super::*;
    use iac_forge::ir::{AuthInfo, CrudInfo, IdentityInfo};
    use std::collections::BTreeMap;

    fn provider() -> IacProvider {
        IacProvider {
            name: "akeyless".to_string(),
            description: String::new(),
            version: "1.0.0".to_string(),
            auth: AuthInfo::default(),
            skip_fields: vec![],
            platform_config: BTreeMap::new(),
        }
    }

    fn auth_method() -> IacResource {
        IacResource {
            name: "akeyless_auth_method_api_key".to_string(),
            description: "Manages an API key auth method".to_string(),
            category: "auth_method".to_string(),
            crud: CrudInfo {
                create_endpoint: "/auth-method-create-api-key".to_string(),
                create_schema: "authMethodCreateApiKey".to_string(),
                update_endpoint: Some("/auth-method-update-api-key".to_string()),
                update_schema: Some("authMethodUpdateApiKey".to_string()),
                read_endpoint: "/get-auth-method".to_string(),
                read_schema: "getAuthMethod".to_string(),
                read_response_schema: Some("AuthMethod".to_string()),
                delete_endpoint: "/delete-auth-method".to_string(),
                delete_schema: "deleteAuthMethod".to_string(),
            },
            attributes: vec![
                IacAttribute {
                    api_name: "name".to_string(),
                    canonical_name: "name".to_string(),
                    description: "Auth method name".to_string(),
                    iac_type: IacType::String,
                    required: true,
                    optional: false,
                    computed: false,
                    sensitive: false,
                    json_encoded: false,
                    immutable: true,
                    default_value: None,
                    enum_values: None,
                    read_path: None,
                    update_only: false,
                },
                IacAttribute {
                    api_name: "access-id".to_string(),
                    canonical_name: "access_id".to_string(),
                    description: "The auth method access ID".to_string(),
                    iac_type: IacType::String,
                    required: false,
                    optional: false,
                    computed: true,
                    sensitive: false,
                    json_encoded: false,
                    immutable: false,
                    default_value: None,
                    enum_values: None,
                    read_path: None,
                    update_only: false,
                },
            ],
            identity: IdentityInfo {
                id_field: "name".to_string(),
                import_field: "name".to_string(),
                force_replace_fields: vec!["name".to_string()],
            },
        }
    }

    #[test]
    fn types_file_contains_all_managed_resource_sections() {
        let code = render_resource_types(&auth_method(), &provider());
        assert!(code.starts_with("// Code generated by crossplane-forge. DO NOT EDIT."));
        assert!(code.contains("package v1alpha1"));
        assert!(code.contains("type AuthMethodApiKeyParameters struct"));
        assert!(code.contains("type AuthMethodApiKeyObservation struct"));
        assert!(code.contains("type AuthMethodApiKeySpec struct"));
        assert!(code.contains("type AuthMethodApiKeyStatus struct"));
        assert!(code.contains("type AuthMethodApiKey struct"));
        assert!(code.contains("type AuthMethodApiKeyList struct"));
        assert!(code.contains("xpv1.ResourceSpec"));
        assert!(code.contains("xpv1.ResourceStatus"));
        // ForProvider + AtProvider wiring
        assert!(code.contains("ForProvider AuthMethodApiKeyParameters"));
        assert!(code.contains("AtProvider AuthMethodApiKeyObservation"));
        // kubebuilder annotations (managed-resource convention)
        assert!(code.contains("// +kubebuilder:object:root=true"));
        assert!(code.contains("// +kubebuilder:subresource:status"));
        assert!(code.contains("READY"));
        assert!(code.contains("SYNCED"));
    }

    #[test]
    fn parameters_includes_user_set_fields_and_excludes_computed() {
        let code = render_parameters(&auth_method(), "AuthMethodApiKey");
        assert!(code.contains("Name string `json:\"name\"`"));
        assert!(!code.contains("AccessId")); // computed → not in Parameters
    }

    #[test]
    fn observation_includes_only_computed_fields() {
        let code = render_observation(&auth_method(), "AuthMethodApiKey");
        assert!(code.contains("AccessId *string"));
        assert!(!code.contains("Name string"));
    }

    #[test]
    fn required_field_emits_kubebuilder_validation() {
        let code = render_parameters(&auth_method(), "AuthMethodApiKey");
        assert!(code.contains("// +kubebuilder:validation:Required"));
    }

    #[test]
    fn immutable_field_emits_xvalidation() {
        let code = render_parameters(&auth_method(), "AuthMethodApiKey");
        assert!(code.contains("XValidation:rule=\"self == oldSelf\""));
    }

    #[test]
    fn groupversion_info_registers_kind_and_list() {
        let code = render_groupversion_info(
            &auth_method(),
            &provider(),
            "authmethod.akeyless.crossplane.io",
            "v1alpha1",
        );
        assert!(code.contains("// +groupName=authmethod.akeyless.crossplane.io"));
        assert!(code.contains("Group: \"authmethod.akeyless.crossplane.io\", Version: \"v1alpha1\""));
        assert!(code.contains("&AuthMethodApiKey{}"));
        assert!(code.contains("&AuthMethodApiKeyList{}"));
    }

    #[test]
    fn paths_match_crossplane_layout() {
        assert_eq!(
            types_file_path(&auth_method(), &provider()),
            "apis/authmethodapikey/v1alpha1/auth_method_api_key_types.go"
        );
        assert_eq!(
            groupversion_file_path(&auth_method(), &provider()),
            "apis/authmethodapikey/v1alpha1/groupversion_info.go"
        );
    }
}
